---
title: "2.1_GSEA"
author: "Ronnie Li"
date: "`r Sys.Date()`"
output: html_document
---

### Gene Set Enrichment ANalysis (GSEA)

This script runs GSEA on the age-associated genes in the GTEx 
Consortium v10 dataset.

```{r setup, include=FALSE}
here::i_am("scripts/2.1_GSEA.Rmd")
knitr::opts_chunk$set(echo = TRUE)

suppressMessages(library(tidyverse))
suppressMessages(library(fgsea))
suppressMessages(library(msigdbr))
suppressMessages(library(patchwork))

# ggplot2 theme for manuscript
theme_ms <- function(base_size = 14, base_family = "") {
  ggplot2::theme_classic(base_size = base_size, base_family = base_family) +
    ggplot2::theme(
      panel.border = ggplot2::element_rect(colour = "black", fill = NA, linewidth = 1),
      strip.background = ggplot2::element_rect(linetype = "blank"),
      plot.title = ggplot2::element_text(size = ggplot2::rel(1)),
      axis.text = ggplot2::element_text(size = ggplot2::rel(0.75)),
      panel.grid.minor = ggplot2::element_line(colour = "grey90", linewidth = 0.5),
      panel.grid.major = ggplot2::element_line(colour = "grey90", linewidth = 0.5),
      complete = FALSE
    )
}

# directories
result_dir <- "data/p_value"
plot_dir <- "figures"

# get MSigDB genes
geneset <- msigdbr(db_species = "HS", species = "human", 
                   collection = "C2" , subcollection = "CP:WIKIPATHWAYS")
gene_list <- split(geneset$gene_symbol, f = geneset$gs_description)

```

### Main GSEA function
Define GSEA function to use `fgsea()` on predefined gene set

```{r}

doGSEA <- function(pval_table, gene_list, tissue_name = "") {
  
  df <- pval_table %>%
    dplyr::select(Gene, p_value_age, age_coef) %>%
    dplyr::mutate(
      p_value_age = as.numeric(p_value_age),
      age_coef = as.numeric(age_coef),
      rank = sign(age_coef) * -log10(p_value_age)
    ) %>%
    dplyr::filter(is.finite(rank)) %>%
    dplyr::arrange(desc(rank))
  
  # create named vector of statistics
  set.seed(1234)
  Z <- setNames(df$rank, df$Gene)
  
  # fgsea() function
  gsea_res <- fgseaMultilevel(pathways = gene_list, stats = Z, 
                              maxSize = 300, nPermSimple = 10000, nproc = 1)
  
  # create plot
  to_plot <- gsea_res %>%
    dplyr::arrange(pval) %>%
    dplyr::mutate(pathway = str_wrap(gsub("_"," ",pathway), width = 40),
                  Direction = ifelse(NES > 0, "Upregulated", "Downregulated")) %>%
    split(., .$Direction) %>%
    purrr::map(., ~ .x %>% arrange(pval) %>% slice_head(n = 8)) %>%
    Reduce(rbind, .) %>%
    dplyr::mutate(Direction = factor(Direction, levels = c("Upregulated","Downregulated")))
  
  p <- ggplot(to_plot, aes(x = -log10(padj), y = reorder(pathway, -pval), 
                           size = size, colour = abs(NES))) + 
    geom_point(alpha = 0.5) +
    geom_vline(xintercept = -log10(0.05), linetype = 'dashed', 
               colour = 'darkorange', linewidth = 0.8) +
    facet_grid(rows = vars(Direction), space = 'free', scale = 'free') + 
    theme_ms() +
    labs(x = '-log10 FDR', y = 'Pathway', title = str_to_title(tissue_name),
         colour = "|NES|", size = "Gene set size")

  res <- list("result" = gsea_res, "plot" = p)
  return(res)
}

app_dir <- here::here()
data_dir <- file.path(app_dir, "data")
tissue_file <- file.path(data_dir, "tissue_names.txt")
tissues <- readLines(tissue_file)
tissue_list <- c("brain_cortex","brain_frontal_cortex_BA9",
                 "brain_cerebellum","brain_hippocampus",
                 "breast_mammary_tissue",
                 "liver","lung","whole_blood")

gsea_plots <- lapply(tissues, function(t) {
  tissue_name <- gsub(" ","_",t)
  pval_table <- read.csv(here::here(result_dir, sprintf("%s_pvalue_results.csv", tissue_name)), header = TRUE,   na.strings = c("", "NA", "--", "Inf")
)
  res <- doGSEA(pval_table, gene_list = gene_list, tissue_name = tissue_name)
  if (!dir.exists(plot_dir)) dir.create(plot_dir, recursive = TRUE)
  ggsave(here::here(plot_dir, sprintf("DAS_%s_GSEA.png", t)),
         plot = res$plot, scale = 1, width = 9, height = 8, dpi = 400, bg = 'white')
  return(res$plot)
})


```

